sudo: false

language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 7.0
    - "hhvm"

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

before_script:
    - if [ "$TRAVIS_PHP_VERSION" == 5.5 ] || [ "$TRAVIS_PHP_VERSION" == 5.4 ] || [ "$TRAVIS_PHP_VERSION" == 7.0 ]; then autodetect | pecl install imagick; fi
    - if [ "$TRAVIS_PHP_VERSION" == 5.3 ]; then autodetect | pecl install imagick-3.0.1; fi
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer install --prefer-source

script:
    - mkdir -p build/logs; phpunit --coverage-clover build/logs/clover.xml;

after_script:
    - php vendor/bin/coveralls -v;

after_success:
    - coveralls;
